name: npm publish

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: purescript-contrib/setup-purescript@main
      - run: spago test

      - run: echo "TODO publish"
