name: publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: purescript-contrib/setup-purescript@main

      - run: yarn
      - run: spago test

      - run: echo "TODO publish"
