name: Test

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  upload-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: purescript-contrib/setup-purescript@main
      - run: spago test
